name: Release to NPM

on:
  push:
    branches:
      - main


permissions: 
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Publish version
        run: echo "RELEASE_VERSION=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: GIT Configuration
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      
      - name: Install pnpm
        run: npm install -g pnpm

      - name: NPM version bump
        run: pnpm version --no-git-tag-version ${{ steps.publish_version.outputs.RELEASE_VERSION }}

      # - name: push to github
      #   run: |
      #     git add .
      #     git commit -m "chore: publish version ${{ steps.publish_version.outputs.RELEASE_VERSION }}"
      #     git push origin HEAD:${{ github.event.repository.default_branch }}
          
      - name: Install dependencies
        run: pnpm install

      - name: "Build package"
        run: pnpm build

      - name: Run Semantic Release
        env: 
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
          pnpm run release
      - name: Commit and push version updates
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add package.json
          git commit -m "chore(release): ${RELEASE_VERSION}"
          git push origin main
        env:
          RELEASE_VERSION: ${{ steps.release.outputs.version }}